export { BIOME_SYNERGIES } from './biomeSynergies'
export type { BiomeSynergyDef } from './biomeSynergies'
export { STYLE_MAP } from './styleMap'
export { CHARACTER_MECHANICS } from './characterMechanics'
export type { CharacterMechanic, BallPrefs } from './characterMechanics'
export { PASSIVE_BALL_SYNERGIES } from './passiveBallSynergies'
export type { PassiveBallSynergyDef } from './passiveBallSynergies'
